export const ON_TIME_INTERVAL = 'ON_TIME_INTERVAL';
export const ON_MOUSE_OVER = 'ON_MOUSE_OVER';
export const ON_BUTTON_CLICK = 'ON_BUTTON_CLICK';

export const ON_OPEN_RWDNAVBOX = 'ON_OPEN_RWDNAVBOX';
export const ON_CLOSE_RWDNAVBOX = 'ON_CLOSE_RWDNAVBOX';
